config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: 'User',
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', to: 'omniauth_callbacks#setup'
  end

  root 'home#show'

  resource :home, only: :show, controller: :home

  namespace :user do
    resources :expenses do
      collection do
        post :import
      end
    end
    resources :weekly_expenses, only: :index
    resources :weekly_expenses_mails do
      collection do
        get :send_expenses_mail
      end
    end
    resources :groups_expenses, only: [:show, :index]
    resources :weekly_groups_expenses, only: [:index, :show]
    resources :weekly_groups_expenses_mails do
      member do
        get :send_group_expenses_mail
      end
    end
    resources :shop_items, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :currencies, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :currency_exchange, only: :index
  resources :currency_exchange_settings, only: [:create, :destroy]
  resources :currency_rates, only: :index
  resources :groups
  resources :expenses_categories, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :shops, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :google_search, only: :index
  resources :google_queries, only: :index do
    collection do
      get :send_statistics_mail
    end
  end

  namespace :api do
    namespace :v1 do
      resources :currencies, only: [:index, :show, :create, :update, :destroy]
      resources :expenses, only: [:index, :show, :create, :update, :destroy]
      resources :expenses_categories, only: [:index, :show, :create, :update, :destroy]
      resources :groups, only: [:index, :show, :create, :update, :destroy]
      resources :shops, only: [:index, :show, :create, :update, :destroy]
      resources :shop_items, only: [:index, :show, :create, :update, :destroy]
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :current_password, :skip_password_validation, :skip_email_validation

  validates_presence_of :email, unless: :skip_email_validation
  validates_uniqueness_of :email, allow_blank: true, if: :email_changed?
  validates_format_of :email, with: Devise.email_regexp, allow_blank: true, if: :email_changed?

  validates_presence_of :password, unless: :skip_password_validation
  validates_confirmation_of :password, unless: :skip_password_validation
  validates_length_of :password, within: Devise.password_length, allow_blank: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  has_many :expenses
  has_many :groups, through: :memberships
  has_many :identities
  has_many :memberships, inverse_of: :user
  has_many :owned_groups, class_name: 'Group', foreign_key: :owner_id
  has_many :shop_items

  def twitter
    identities.where(provider: "twitter").first
  end

  def facebook
    identities.where(provider: "facebook").first
  end

  def google_oauth2
    identities.where(provider: "google_oauth2").first
  end

  def total_price_for_week(date)
    expenses.for_week(date).sum(:price_value)
  end

  def total_price_for_future_expenses
    shop_items.sum(:price_value)
  end

  def planned_total_price_for_day(date)
    shop_items.for_day(date).sum(:price_value)
  end

  def compare_expenses_to_last_week(date)
    if total_price_for_week(date) > total_price_for_week(date - 1.week)
      "Your weekly expenses were greater than expenses from last week."
    else
      "Your weekly expenses were lower than expenses from last week."
    end
  end
end

app/controllers/api/v1/expenses_controller.rb
class Api::V1::ExpensesController < ApplicationController
  respond_to :json

  expose(:expenses)
  expose(:expense, attributes: :expense_params)

  def index
    render json: expenses
  end

  def show
    render json: expense
  end

  def create
    if expense.save
      render json: expense
    else
      render json: {errors: expense.errors}
    end
  end

  def update
    if expense.save
      render json: expense
    else
      render json: {errors: expense.errors}
    end
  end

  def destroy
    expense.destroy
    render json: {message: 'expense destroyed'}
  end

  private

  def expense_params
    params.require(:expense).permit(:currency_id,
                                    :description,
                                    :expenses_category_id,
                                    :name,
                                    :price_value,
                                    :shop_id,
                                    :user_id)
  end
end

app/controllers/user/expenses_controller.rb
class User::ExpensesController < User::UserController
  before_action :check_ownership, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  expose(:expenses) { current_user.expenses }
  expose_decorated(:expense, attributes: :expense_params)
  expose(:expenses_categories) { ExpensesCategory.all }
  expose(:expenses_import) { ExpensesImport.new }
  expose(:total_price_category) do
    expenses_categories.map { |category| category.expenses.for_user(current_user).sum(:price_value).to_f }
  end

  def new
    respond_modal_with expense
  end

  def edit
    respond_modal_with expense
  end

  def create
    expense.save
    respond_modal_with expense, location: user_expenses_path
  end

  def update
    expense.save
    respond_modal_with expense, location: user_expenses_path
  end

  def destroy
    expense.destroy
    respond_to do |format|
      format.html { redirect_to user_expenses_path }
      format.js
    end
  end

  def import
    if params[:expenses_import] && params[:expenses_import][:file]
      begin
        ExpensesImport.new(params[:expenses_import][:file]).import_for(current_user)
        redirect_to user_expenses_path, notice: 'Success.'
      rescue ExpensesImport::ImportError => e
        redirect_to user_expenses_path, alert: e.message
      end
    else
      redirect_to user_expenses_path, alert: 'You have to upload file.'
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:currency_id,
                                    :description,
                                    :expenses_category_id,
                                    :name,
                                    :photo,
                                    :price_value,
                                    :shop_id)
  end

  def check_ownership
    begin
      expense
    rescue
      redirect_to user_expenses_path, alert: 'You are not authorized to see this expense'
    end
  end
end

app/controllers/user/groups_expenses_controller.rb
class User::GroupsExpensesController < User::UserController
  before_action :check_access_to_group, only: [:show]
  expose(:groups) { current_user.groups }
  expose(:group)
  expose(:q) { Expense.ransack(params[:q]) }
  expose(:expenses) { q.result.for_group(group).includes(:user) }
  expose(:expenses_by_category) { expenses.group_by(&:expenses_category) }

  private

  def check_access_to_group
    begin
      group
    rescue
      redirect_to user_groups_expenses_path, alert: 'You are not authorized to see this group'
    end
  end
end

app/controllers/user/shop_items_controller.rb
class User::ShopItemsController < User::UserController
  before_action :check_ownership, only: [:edit, :update, :destroy]
  respond_to :html, :json

  expose(:shop_items) { current_user.shop_items }
  expose_decorated(:shop_item, attributes: :shop_item_params)
  expose(:shop_items_for_day) { current_user.shop_items.for_day(date) }
  expose(:date) { params[:date] ? Date.parse(params[:date]) : Date.today }

  def new
    respond_modal_with shop_item
  end

  def edit
    respond_modal_with shop_item
  end

  def create
    shop_item.save
    respond_modal_with shop_item, location: user_shop_items_path
  end

  def update
    shop_item.save
    respond_modal_with shop_item, location: user_shop_items_path
  end

  def destroy
    shop_item.destroy
    redirect_to user_shop_items_path
  end

  private

  def shop_item_params
    params.require(:shop_item).permit(:currency_id,
                                    :expenses_category_id,
                                    :name,
                                    :price_value,
                                    :purchased_on,
                                    :shop_id)
  end

  def check_ownership
    begin
      shop_item
    rescue
      redirect_to user_shop_items_path, alert: 'You are not authorized to see this shop item'
    end
  end
end

app/controllers/user/user_controller.rb
class User::UserController < ApplicationController
  before_action :check_current_user

  private

  def check_current_user
    redirect_to root_path, alert: 'You have to be logged in to see this page.' unless current_user
  end
end

app/controllers/user/weekly_expenses_controller.rb
class User::WeeklyExpensesController < User::UserController

  expose(:expenses) { current_user.expenses }
  expose(:expenses_for_week) { expenses.for_week(date) }
  expose(:date) { params[:date] ? Date.parse(params[:date]) : Date.today }

  def index
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'weekly_report', layout: "pdf.html.haml"
      end
    end
  end
end

app/controllers/user/weekly_expenses_mails_controller.rb
class User::WeeklyExpensesMailsController < User::UserController
  expose(:user) { current_user }
  expose(:date) { params[:date] ? Date.parse(params[:date]) : Date.today }

  def send_expenses_mail
    UserMailerWorker.perform_async(user.id, date.to_s)
    redirect_to :back
  end
end

app/controllers/user/weekly_groups_expenses_controller.rb
class User::WeeklyGroupsExpensesController < User::UserController
  expose(:groups) { current_user.groups }
  expose(:group)
  expose(:expenses) { Expense.for_group(group) }
  expose(:expenses_for_week) { expenses.for_week(date) }
  expose(:date) { params[:date] ? Date.parse(params[:date]) : Date.today }

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'weekly_report', layout: "pdf.html.haml"
      end
    end
  end

  def send_group_expenses_mail
    GroupMailer.group_info_email(date, group, expenses_for_week).deliver
    redirect_to user_weekly_groups_expense_path(group.id)
  end
end

app/controllers/user/weekly_groups_expenses_mails_controller.rb
class User::WeeklyGroupsExpensesMailsController < User::UserController
  expose(:groups) { current_user.groups }
  expose(:group)
  expose(:expenses) { Expense.for_group(group) }
  expose(:expenses_for_week) { expenses.for_week(date) }
  expose(:date) { params[:date] ? Date.parse(params[:date]) : Date.today }

  def send_group_expenses_mail
    GroupMailerWorker.perform_async(date.to_s, group.id)
    redirect_to :back
  end
end

app/views/user/expenses/_form.html.haml
= simple_form_for [:user, expense], remote: request.xhr?, html: { data: { modal: true }, multipart: true } do |f|
  = f.input :name
  = f.input :price_value
  = f.association :currency, include_blank: false
  = f.association :shop, include_blank: false
  = f.association :expenses_category, include_blank: false
  = f.input :description
  = f.input :photo, as: :file
  = f.submit

app/views/user/expenses/destroy.js.haml
$('#expense_#{expense.id}').remove();

app/views/user/expenses/edit.html.haml
%h1 Edit expense
= render 'form'

app/views/user/expenses/index.html.haml
:javascript
  $(function () {
    $('#expenses_chart').highcharts({
        chart: {
          type: 'column'
        },
        title: {
          text: 'All expenses'
        },
        xAxis: {
          categories: #{expenses_categories.pluck(:name)},
          title: { text:'Categories' }
          },
        yAxis: {
          min: 0,
          title: {
            text: 'Price value'
          }
        },
        tooltip: {
          headerFormat: '<b>{point.x}</b><br/>',
          pointFormat: '{series.name}: {point.y}'
        },
        plotOptions: {
          column: {
            stacking: 'normal'
          }
        },
        series: [

        {
          name: 'Price',
          data: #{total_price_category}
        }]
      });
    });

#expenses_chart{:style => "min-width: 310px; height: 400px; margin: 0 auto"};

%h1 Expenses
%p= link_to 'New expense', new_user_expense_path, data: { modal: true }, class: 'btn btn-success'
%p= link_to 'Weekly expenses', user_weekly_expenses_path, class: 'btn btn-info'

= simple_form_for expenses_import, as: :expenses_import, url: import_user_expenses_path do |f|
  = f.input :file, as: :file
  = f.submit

%table.table.table-striped
  %tr
    %th Name
    %th Price
    %th Currency
    %th Description
    %th Shop
    %th Category
    %th Actions
  - expenses.each do |expense|
    %tr{id: "expense_#{expense.id}"}
      %td= expense.name
      %td= expense.decorate.price
      %td= expense.currency.name
      %td= expense.decorate.description_for_display
      %td= expense.shop.name
      %td= expense.expenses_category.name
      %td
        = link_to 'Show', user_expense_path(expense.id)
        = link_to 'Edit', edit_user_expense_path(expense.id), data: { modal: true }
        = link_to 'Delete', user_expense_path(expense.id), method: :delete, remote: true, data: {confirm: 'Are you sure?'}
  %tr
    %td TOTAL PRICE
    %td
      %b= price(total_price(expenses))
    %td
    %td
    %td
    %td
    %td

- expenses_categories.each do |category|
  %h3= category.name
  %table.table.table-striped
    %tr
      %th Name
      %th Price
      %th Currency
      %th Description
      %th Shop
      %th Photo
      %th Value %
    - category.expenses.for_user(current_user).each do |expense|
      %tr
        %td= expense.name
        %td= expense.decorate.price
        %td= expense.currency.name
        %td= expense.decorate.description_for_display
        %td= expense.shop.name
        %td= image_tag expense.photo.url(:thumb), size: '50x50'
        %td= percentage_usage(expense, category.expenses.for_user(current_user))
    %tr
      %td TOTAL PRICE
      %td
        %b= price(category.total_price_for_user(current_user))
      %td
      %td
      %td
      %td
      %td

app/views/user/expenses/new.html.haml
%h1 New expense
= render 'form'

app/views/user/expenses/show.html.haml
%h2
  %b= expense.name

%p
  %b Price
  = expense.price

%p
  %b Currency:
  = expense.currency.name

%p
  %b Expenses group:
  = expense.expenses_category.name

%p
  %b Description:
  = expense.description_for_display

%p
  %b Photo:
%p
  = image_tag expense.photo.url