config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: 'User',
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', to: 'omniauth_callbacks#setup'
  end

  root 'home#show'

  resource :home, only: :show, controller: :home

  namespace :user do
    resources :expenses do
      collection do
        post :import
      end
    end
    resources :weekly_expenses, only: :index
    resources :weekly_expenses_mails do
      collection do
        get :send_expenses_mail
      end
    end
    resources :groups_expenses, only: [:show, :index]
    resources :weekly_groups_expenses, only: [:index, :show]
    resources :weekly_groups_expenses_mails do
      member do
        get :send_group_expenses_mail
      end
    end
    resources :shop_items, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :currencies, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :currency_exchange, only: :index
  resources :currency_exchange_settings, only: [:create, :destroy]
  resources :currency_rates, only: :index
  resources :groups
  resources :expenses_categories, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :shops, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :google_search, only: :index
  resources :google_queries, only: :index do
    collection do
      get :send_statistics_mail
    end
  end

  namespace :api do
    namespace :v1 do
      resources :currencies, only: [:index, :show, :create, :update, :destroy]
      resources :expenses, only: [:index, :show, :create, :update, :destroy]
      resources :expenses_categories, only: [:index, :show, :create, :update, :destroy]
      resources :groups, only: [:index, :show, :create, :update, :destroy]
      resources :shops, only: [:index, :show, :create, :update, :destroy]
      resources :shop_items, only: [:index, :show, :create, :update, :destroy]
    end
  end

end

app/controllers/currency_exchange_controller.rb
class CurrencyExchangeController < ApplicationController
  expose(:pln_money) { Money.new(1_00, 'PLN') }
  expose(:eur_money) { Money.new(1_00, 'EUR') }
  expose(:usd_money) { Money.new(1_00, 'USD') }
  expose(:currencies_for_select) { Currency.all.map { |c| [c.name, c.name] } }

  expose(:value) { params[:value] || 0 }
  expose(:base_currency) { params[:base_currency] || 'PLN' }
  expose(:new_currency) { params[:new_currency] || 'PLN' }
  expose(:new_currency_exchange_setting) do
    CurrencyExchangeSetting.new(value: 0, base_currency: 'PLN', new_currency: 'PLN')
  end
  expose(:converted_value) do
    m = Money.new(value, base_currency)
    m.exchange_to(new_currency).to_f * 100
  end
  expose(:currency_exchange_settings) { CurrencyExchangeSetting.all }

  def index
    respond_to do |format|
      format.html
      format.json { render json: {converted_value: converted_value} }
    end
  end
end

app/views/currency_exchange/index.html.haml
%h3 Currency rates
%br
  1 PLN =
  ="#{pln_money.exchange_to(:USD)} USD"

%br
  1 PLN =
  ="#{pln_money.exchange_to(:EUR)} EUR"

%br
  1 USD =
  ="#{usd_money.exchange_to(:PLN)} PLN"

%br
  1 USD =
  ="#{usd_money.exchange_to(:EUR)} EUR"

%br
  1 EUR =
  ="#{eur_money.exchange_to(:PLN)} PLN"

%br
  1 EUR =
  ="#{eur_money.exchange_to(:USD)} USD"
%br
  %table.table.table-striped
    %tr
      %th Settings
      %th Actions
    - currency_exchange_settings.each do |setting|
      %tr
        %td(id="setting_#{setting.id}" data-value="#{setting.value}" data-base-currency="#{setting.base_currency}" data-new-currency="#{setting.new_currency}")
          = setting.decorate.for_display
        %td
          = link_to 'Apply', 'javascript:void(0)', onclick: "setCurrencyExchangeSetting(#{setting.id})"
          = link_to 'Delete', currency_exchange_setting_path(setting), method: :delete, data: {confirm: 'Are you sure?'}

  = simple_form_for new_currency_exchange_setting, id: 'currency_exchange_form' do |f|
    = f.input :value, input_html: {onkeyup: 'calculateConvertedValue()'}
    = f.input :base_currency, collection: currencies_for_select, input_html: {onchange: 'calculateConvertedValue()'}, include_blank: false
    = f.input :new_currency, collection: currencies_for_select, input_html: {onchange: 'calculateConvertedValue()'}, include_blank: false
    = f.submit 'save setting'
    Converted value:
    %span#converted_value_holder
      = converted_value